# Atelier NumPy - IoT & Capteurs

## Contexte
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Ces capteurs mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. Les données collectées doivent être préparées et analysées avant d'être transmises à un futur système de Machine Learning chargé de détecter des situations anormales.
## Objectif général de l'atelier
L'objectif de cet atelier est de maîtriser les bases de **NumPy** (Numerical Python), la bibliothèque fondamentale pour le calcul scientifique en Python. 
À travers cet atelier, nous allons apprendre à :
- Manipuler des tableaux multidimensionnels (vecteurs et matrices).
- Effectuer des opérations mathématiques vectorisées (sans boucles `for`).
- Extraire, filtrer et transformer des données numériques efficacement.
## Structure du notebook
Ce notebook est découpé en plusieurs parties. Chaque partie correspond à une fonctionnalité précise (création de données, indexation, filtrage, calculs statistiques, etc.). 
Les résultats seront sauvegardés et poussés sur GitHub au fur et à mesure.

# Partie 1 : Listes Python vs tableaux NumPy

## Objectif de la partie
Avant de plonger dans les fonctionnalités avancées de NumPy, nous devons comprendre **pourquoi** nous utilisons cette bibliothèque plutôt que les listes classiques de Python.
## Ce qui est attendu
Nous disposons des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8.
1. Nous allons créer une **liste Python** classique pour stocker ces valeurs.
2. Nous allons créer un **tableau NumPy** équivalent.
3. Nous allons multiplier ces deux collections par 2.
4. Nous observerons et noterons la **différence fondamentale** dans le comportement

In [1]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.6 MB 1.7 MB/s eta 0:00:07
   ---- ----------------------------------- 1.6/12.6 MB 1.8 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.6 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.6 MB 1.9 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.6 MB 1.9 MB/s eta 0:00:06
   ---------- ----------------------------- 3.4/12.6 MB 1.8 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.6 MB 1.8 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.6 MB 1.8 MB/s eta 0:00:05
   -------------- --


[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

#Création de liste python et du tableau numpy
temp_py = [24.5, 25.1, 26.3, 27.0, 25.8]
temp_nump = np.array(temp_py)
print("liste_python:" , temp_py)
print("numpy_array:" , temp_nump)

#Multiplication par 2
mult_py = temp_py * 2
mult_nump = temp_nump * 2
print( "liste_python*2:" , mult_py)
print("numpy_array*2:" , mult_nump)

liste_python: [24.5, 25.1, 26.3, 27.0, 25.8]
numpy_array: [24.5 25.1 26.3 27.  25.8]
liste_python*2: [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
numpy_array*2: [49.  50.2 52.6 54.  51.6]


Nous observons et notons la **différence fondamentale** dans le comportement :
   - La liste Python va dupliquer les éléments lors de la multiplication par 2(elle s'allonge).
   - Le tableau NumPy va multiplier mathématiquement chaque valeur de la liste par 2 (calcul vectoriel).

# Partie 2 – Création des données

## Objectif de la partie
Maintenant que nous avons compris la différence entre une liste Python et un tableau NumPy, nous allons apprendre à **générer** des tableaux de données sans avoir à les écrire un par un. 
Dans la vraie vie (et dans l'atelier), on a souvent besoin de créer des tableaux de zéros, de nombres alignés, ou de valeurs aléatoires pour simuler des données de capteurs.
## Ce qui est attendu
Nous allons utiliser les fonctions de création de NumPy pour répondre aux 7 questions suivantes. Chaque question correspond à une situation concrète

In [ ]:
import numpy as np

#Partie 2: Création de données
# 1. Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro
temp_initiale = np.zeros(10)
# 2. Créer un tableau contenant 10 valeurs égales à 1
table_1= np.ones(10)
# 3. Créer un tableau de 10 valeurs initialisées à 25.
table_25 = np.full(10, 25)
# 4. Créer une matrice identité de taille 5 × 5
mat_id = np.eye (5,5)
# 5. Créer les 24 heures (de 0 à 23) de mesure d’une journée
heures = np.arange(24)
# 6. Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
temp_degrés = np.linspace(20, 30, 10)
# 7. Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles
np.random.seed(42)
temp_aléatoires = np.random.uniform(20, 30, 100)

#Affichage des résultats
print("1. Température initiale :", temp_initiale)
print("2. Tableau de 1s :", table_1)
print("3. Tableau de 25s :", table_25)
print("4. Matrice identité :\n", mat_id)
print("5. Heures :", heures)
print("6. Températures régulières : \n", temp_degrés)
print("7. Températures aléatoires: \n", temp_aléatoires)

1. Température initiale : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Tableau de 1s : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
3. Tableau de 25s : [25 25 25 25 25 25 25 25 25 25]
4. Matrice identité :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5. Heures : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
6. Températures régulières : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]
7. Températures aléatoires: [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.976721

# Partie 3 – Exploration des tableaux

## Objectif de la partie
Maintenant que nous savons créer des tableaux de données, nous devons apprendre à les **explorer** et à comprendre leur structure. Dans la vraie vie, quand on reçoit un jeu de données (un tableau NumPy), on a besoin de savoir immédiatement :
- Combien de dimensions il a (est-ce un simple vecteur, une matrice, ou un tableau à plusieurs dimensions ?)
- Combien de valeurs il contient au total.
- Quel est le type des données (nombres entiers, décimaux, texte ?).
- Quelle est sa forme (ex: 24 lignes, ou 24 valeurs sur une seule ligne ?).
Ces informations sont essentielles avant de faire le moindre calcul ou la moindre modification.
## Ce qui est attendu
Nous allons utiliser le tableau des 24 températures d'une journée, créé aléatoirement, puis nous interrogerons ses propriétés à l'aide des attributs suivants :
- `.ndim` : pour connaître le nombre de dimensions.
- `.size` : pour connaître le nombre total d'éléments.
- `.dtype` : pour connaître le type de données (int, float, etc.).
- `.shape` : pour connaître la forme du tableau (nombre de lignes, de colonnes).
L'objectif est de prendre l'habitude de toujours "tâter" les données avant de les manipuler.

In [5]:
import numpy as np
# Partie 3: Exploration des tableaux
# 1.Créer aléatoirement un tableau représentant les 24 températures d'une journée
np.random.seed(42)
temp_journée = np.random.uniform(20, 30, 24)
print("Températures de la journée : \n", temp_journée)
# 2. Déterminer les propriétés suivantes du tableau
# dimension du tableau
dimension = temp_journée.ndim
# nombre de valeurs dans le tableau
nombre_valeurs = temp_journée.size
# type de données du tableau
type_donnees = temp_journée.dtype
# forme du tableau  
forme = temp_journée.shape

# 3. Afficher les résultats
print ("La dimension du tableau est :", dimension)
print ("Le nombre de valeurs dans le tableau est :", nombre_valeurs)
print ("Le type de données du tableau est :", type_donnees)
print ("La forme du tableau est :", forme)

Températures de la journée : 
 [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]
La dimension du tableau est : 1
Le nombre de valeurs dans le tableau est : 24
Le type de données du tableau est : float64
La forme du tableau est : (24,)


# Partie 4 – Indexation et slicing

## Objectif de la partie
Maintenant que nous savons créer et explorer des tableaux, nous devons apprendre à en **extraire des morceaux précis**. C'est une compétence fondamentale en data science 
## Ce qui est attendu
En utilisant le tableau des 24 températures d'une journée (créé dans la Partie 3), nous allons afficher :
1. la première mesure (index 0) ;
2. la dernière mesure (index -1) ;
3. la température de 8h (index 8) ;
4. les températures de 8h à 12h (indices 8 à 12 inclus) ;
5. les températures des 6 premières heures (indices 0 à 5) ;

In [7]:
import numpy as np
# Partie 4: Indexation et slicing
# 1. la première mesure
premiere_mesure = temp_journée[0]   
# 2. la dernière mesure
derniere_mesure = temp_journée[-1]
# 3. La température de 8H
temp_8h = temp_journée[8]
# 4. Les températures de 8H à 12H
temp_8_12 = temp_journée [8:13]
# 5. Les 6 premières températures
six_first = temp_journée [:6]
# 6. Températures des heures paires
pairs_heures = temp_journée [ : :2]

print ("La première mesure est: ", premiere_mesure)
print ("La dernière mesure est: ", derniere_mesure)
print ("La température à 8H est: ", temp_8h)
print ("La tempérture entre 8H et 12H est: ", temp_8_12)
print("Les six premières températures sont: ", six_first)
print ("La température des heures paires est" , pairs_heures)


La première mesure est:  23.745401188473625
La dernière mesure est:  23.663618432936918
La température à 8H est:  26.011150117432088
La tempérture entre 8H et 12H est:  [26.01115012 27.08072578 20.20584494 29.69909852 28.32442641]
Les six premières températures sont:  [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452 ]
La température des heures paires est [23.74540119 27.31993942 21.5601864  20.58083612 26.01115012 20.20584494
 28.32442641 21.81824967 23.04242243 24.31945019 26.11852895 22.92144649]


# Partie 5 – Filtrage booléen

## Objectif de la partie
L'indexation que nous avons vue dans la Partie 4 consiste à extraire des données **par position** (les 3 premières, la 8ème, etc.). Mais dans la vraie vie, on veut souvent extraire des données **selon une condition** : "Donne-moi toutes les températures trop élevées", ou "Donne-moi toutes les températures normales".
Pour cela, NumPy utilise une technique très puissante appelée **filtrage booléen**. On crée un tableau de Vrai/Faux (booléens), puis on l'utilise comme "masque" pour ne garder que les valeurs Vrai.
## Ce qui est attendu
À partir du tableau des 24 températures d'une journée (créé dans la Partie 3), nous allons :
1. Afficher les températures **supérieures à 30 °C**.
2. Afficher les températures **"normales"** c'est-à-dire comprises **entre 20 °C et 30 °C** (inclus).
3. Supposons qu'une température supérieure à 35 °C soit **anormale**. Créer un tableau de booléens nommé `anomalies` qui précise, pour chaque heure, si la température est anormale (True) ou non (False).
4. Déterminer, à l'aide de `anomalies`, le **nombre** de températures anormales.

In [ ]:
import numpy as np

# Partie 5: Filtrage booléen
# 1. Afficher les températures supérieures à 30 °C
np.random.seed (42)
temp_journée= np.random.uniform (20, 30, 24)
print ("temp_journée: ", temp_journée)
# Affichage du masque de tri
masque_over_30 = temp_journée > 30
temp_over_30 = temp_journée[masque_over_30] 
print ("1. Températures > 30°C :", temp_over_30)

# 2. Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

condition_min = temp_journée >= 20
condition_max = temp_journée <= 30
masque_normal = condition_min & condition_max
temp_normales = temp_journée[masque_normal]
print("2. Températures normales (20-30) :", temp_normales)
# 3. Création du tableau des anomalies (Température > 35°C)
# On stocke le résultat (Vrai/Faux) dans une variable appelée "anomalies".
anomalies = temp_journée > 35
table_anomalies = temp_journée [anomalies]
print("3. Tableau des anomalies:", table_anomalies)
# 4. Détermination du nombre de température anormales
nombre_anomalies = np.sum(table_anomalies)
print("4. Nombre de températures anormales (>35°C) :", int(nombre_anomalies))


temp_journée:  [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]
1. Températures > 30°C : []
2. Températures normales (20-30) : [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843]
3. Tableau des anomalies: []
4. Nombre de températures anormales (>35°C) : 0


# Partie 6 – Manipulation des dimensions

## Objectif de la partie
Jusqu'à présent, nous avons travaillé avec des tableaux à une seule dimension (des vecteurs). Mais dans la vraie vie, les données des capteurs sont souvent organisées en **matrices** (2 dimensions) : les lignes représentent les capteurs, et les colonnes représentent les heures.
Dans cette partie, nous allons :
- Créer une matrice 2D.
- Apprendre à changer sa forme (l'aplatir, la transposer).
- Extraire des lignes (un capteur spécifique).
- Extraire des colonnes (une heure spécifique).
- Extraire une sous-matrice (un groupe de capteurs sur une plage horaire précise).
## Ce qui est attendu
On suppose qu'on a 5 capteurs.

1. Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée (5 capteurs × 24 heures).
2. Transformer la matrice en un tableau unidimensionnel (aplatir).
3. Déterminer la transposée de la matrice.
4. Extraire toutes les mesures du capteur 1.
5. Extraire toutes les mesures du capteur 5.
6. Extraire les mesures de tous les capteurs à 10h.
7. Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.

In [34]:
import numpy as np
# 1. Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée
np.random.seed(42)
matrice_temp = np.round(np.random.uniform(20, 30, size= (5,24)), 2)
print ("La matrice de température des 5 capteurs est: ", matrice_temp)
# 2. Transformer la matrice en un tableau unidimensionnel
table_unidim = matrice_temp.flatten()
print("La table unidimensionnelle est: ", table_unidim)
# 3. Déterminer la transposée de la matrice
table_transpose = matrice_temp.T
print("La Table transposée est: ", table_transpose)
# 4. Extraire toutes les mesures du capteur 1
capteur_1 = matrice_temp [0]
print("Le capteur 1 affiche: ",capteur_1)
# 5. Extraire toutes les mesures du capteur 5
capteur_5 = matrice_temp [4]
print("Le capteur 5 affiche: ",capteur_5)
# 6. Extraire les mesures de tous les capteurs à 10H
all_capteurs_10H = matrice_temp [:, 10]
print("Les capteurs affichent à 10H: ", all_capteurs_10H)
# 7. Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.
capteur2_4 = matrice_temp[1:4, 8:12]
print("Les mesures des capteurs 2 à 4 entre 8H et 12H sont: ", capteur2_4)



La matrice de température des 5 capteurs est:  [[23.75 29.51 27.32 25.99 21.56 21.56 20.58 28.66 26.01 27.08 20.21 29.7
  28.32 22.12 21.82 21.83 23.04 25.25 24.32 22.91 26.12 21.39 22.92 23.66]
 [24.56 27.85 22.   25.14 25.92 20.46 26.08 21.71 20.65 29.49 29.66 28.08
  23.05 20.98 26.84 24.4  21.22 24.95 20.34 29.09 22.59 26.63 23.12 25.2 ]
 [25.47 21.85 29.7  27.75 29.39 28.95 25.98 29.22 20.88 21.96 20.45 23.25
  23.89 22.71 28.29 23.57 22.81 25.43 21.41 28.02 20.75 29.87 27.72 21.99]
 [20.06 28.15 27.07 27.29 27.71 20.74 23.58 21.16 28.63 26.23 23.31 20.64
  23.11 23.25 27.3  26.38 28.87 24.72 21.2  27.13 27.61 25.61 27.71 24.94]
 [25.23 24.28 20.25 21.08 20.31 26.36 23.14 25.09 29.08 22.49 24.1  27.56
  22.29 20.77 22.9  21.61 29.3  28.08 26.33 28.71 28.04 21.87 28.93 25.39]]
La table unidimensionnelle est:  [23.75 29.51 27.32 25.99 21.56 21.56 20.58 28.66 26.01 27.08 20.21 29.7
 28.32 22.12 21.82 21.83 23.04 25.25 24.32 22.91 26.12 21.39 22.92 23.66
 24.56 27.85 22.   25.14 25.92

# Partie 7 – Concaténation
## Objectif de la partie
Dans la Partie 6, nous avions 5 capteurs dans un premier bâtiment. Maintenant, on ajoute un **second bâtiment** avec 3 capteurs supplémentaires. Notre objectif est de **fusionner** ces deux ensembles de données en une seule grande matrice qui contient les 8 capteurs.
La concaténation est l'opération qui consiste à "coller" deux tableaux ensemble, soit verticalement (en ajoutant des lignes), soit horizontalement (en ajoutant des colonnes).

In [7]:
import numpy as np
# 1. Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée
np.random.seed(42)
matrice_temp = np.round(np.random.uniform(20, 30, size= (5,24)), 2)
print ("La matrice de température des 5 capteurs est: ", matrice_temp)

np.random.seed(42)
matrice_temp_bat2 = np.round(np.random.uniform(20, 30, size= (3,24)), 2)
print ("La matrice de température des 3 capteurs est: \n", matrice_temp_bat2)
# Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée
# Concaténation par np.concatenate
table_concat_1 = np.concatenate([matrice_temp, matrice_temp_bat2], axis=0)
print ("Le tableau concaténer est : \n", table_concat_1)
# Concaténation avec np.vstack
table_contact_2= np.vstack((matrice_temp, matrice_temp_bat2))
print("Le tableau concaténer avec np.vstack est: \n", table_contact_2)  

La matrice de température des 5 capteurs est:  [[23.75 29.51 27.32 25.99 21.56 21.56 20.58 28.66 26.01 27.08 20.21 29.7
  28.32 22.12 21.82 21.83 23.04 25.25 24.32 22.91 26.12 21.39 22.92 23.66]
 [24.56 27.85 22.   25.14 25.92 20.46 26.08 21.71 20.65 29.49 29.66 28.08
  23.05 20.98 26.84 24.4  21.22 24.95 20.34 29.09 22.59 26.63 23.12 25.2 ]
 [25.47 21.85 29.7  27.75 29.39 28.95 25.98 29.22 20.88 21.96 20.45 23.25
  23.89 22.71 28.29 23.57 22.81 25.43 21.41 28.02 20.75 29.87 27.72 21.99]
 [20.06 28.15 27.07 27.29 27.71 20.74 23.58 21.16 28.63 26.23 23.31 20.64
  23.11 23.25 27.3  26.38 28.87 24.72 21.2  27.13 27.61 25.61 27.71 24.94]
 [25.23 24.28 20.25 21.08 20.31 26.36 23.14 25.09 29.08 22.49 24.1  27.56
  22.29 20.77 22.9  21.61 29.3  28.08 26.33 28.71 28.04 21.87 28.93 25.39]]
La matrice de température des 3 capteurs est: 
 [[23.75 29.51 27.32 25.99 21.56 21.56 20.58 28.66 26.01 27.08 20.21 29.7
  28.32 22.12 21.82 21.83 23.04 25.25 24.32 22.91 26.12 21.39 22.92 23.66]
 [24.56 27.8

# Partie 8 – Calcul scientifique

## Objectif de la partie
Maintenant que nous savons manipuler et extraire des données, nous allons utiliser les fonctions mathématiques de NumPy pour analyser les températures. Ces calculs (moyenne, écart-type, normalisation) sont le **cœur de la data science** : ils permettent de résumer l'information et de préparer les données pour les algorithmes de Machine Learning.

In [14]:
import numpy as np
# 1. Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l’écart-type
np.random.seed(42)
temp_journée = np.round(np.random.uniform(20, 30, 24), 2)
print (temp_journée)
# Le minimum 
min_temp_journée = np.min(temp_journée)
max_temp_journée = np.max(temp_journée)
sum_temp_journée = np.sum(temp_journée)
moy_temp_journée = np.mean(temp_journée)
med_temp_journée = np.median(temp_journée)
var_temp_journée = np.var(temp_journée)
std_temp_journée = np.std(temp_journée)
print("La température minimale dans la journée est: ", min_temp_journée)
print("La température maximale dans la journée est: ", max_temp_journée)
print("La somme des températures dans la journée est: ", sum_temp_journée)
print("La moyenne des températures dans la journée est: ", moy_temp_journée)
print("La médiane des températures dans la journée est: ", med_temp_journée)
print("La variance des températures dans la journée est: ", var_temp_journée)
print("L'écart-type des températures dans la journée est: ", std_temp_journée)

# 2. Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écarttype du tableau standardisé
temp_standardisee = (temp_journée - moy_temp_journée) / std_temp_journée
print ("Le tableau standarisée est: ", temp_standardisee)

# Vérification
moyenne_std = np.round(np.mean(temp_standardisee))
print ("La moyenne standarisée est: ",abs(moyenne_std))
ecart_std = np.std(temp_standardisee)
print ("L'écart-type standarisée est: ",ecart_std)
# 3. Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé
temp_normalisée = (temp_journée - min_temp_journée) / (max_temp_journée - min_temp_journée)
print ("La température normalisée est: ", temp_normalisée)

# Vérification
min_norm = np.min(temp_normalisée)
print (" Le Minimum du tableau normalisé est: ", min_norm)
max_norm = np.max(temp_normalisée)
print (" Le maximum du tableau normalisé est: ", min_norm)
# 4. Convertir le tableau initial en Fahrenheit
temp_fahrenheit = temp_journée * (9/5) + 32
print("Le tableau en celsuis Fareinheit est: ", temp_fahrenheit)






[23.75 29.51 27.32 25.99 21.56 21.56 20.58 28.66 26.01 27.08 20.21 29.7
 28.32 22.12 21.82 21.83 23.04 25.25 24.32 22.91 26.12 21.39 22.92 23.66]
La température minimale dans la journée est:  20.21
La température maximale dans la journée est:  29.7
La somme des températures dans la journée est:  585.63
La moyenne des températures dans la journée est:  24.40125
La médiane des températures dans la journée est:  23.705
La variance des températures dans la journée est:  8.135919270833334
L'écart-type des températures dans la journée est:  2.852353286469496
Le tableau standarisée est:  [-0.22832024  1.79106495  1.02327787  0.55699622 -0.99610732 -0.99610732
 -1.33968328  1.4930654   0.56400797  0.93913682 -1.46940073  1.85767662
  1.37386558 -0.79977821 -0.90495452 -0.90144864 -0.47723752  0.29756132
 -0.02848525 -0.52281392  0.60257262 -1.05570723 -0.51930804 -0.25987314]
La moyenne standarisée est:  0.0
L'écart-type standarisée est:  1.0
La température normalisée est:  [0.37302424 0.97997

# Partie 9 – Broadcasting

## Objectif de la partie
Nous avons vu qu’on peut multiplier un tableau par un nombre (ex: `tableau * 2`) et que ce nombre s’applique à toutes les cases. C’est un cas particulier de **broadcasting** (diffusion).
Le broadcasting va plus loin : il permet d’appliquer une opération entre deux tableaux de **formes différentes**, à condition qu’ils soient "compatibles". Ici, nous allons appliquer une **correction différente pour chaque capteur** sur 3 jours de mesures.
## Ce qui est attendu
1. Créer aléatoirement la matrice `temperatures_vsd` représentant les températures mesurées un **vendredi, samedi et dimanche successifs** dans le **2nd bâtiment** (qui possède 3 capteurs). Cette matrice aura donc une forme de **(3 jours, 3 capteurs)**.
2. On suppose que les valeurs de calibration des capteurs sont stockées dans le tableau `correction = np.array([1, -0.5, 0.2])`. 
   Appliquer automatiquement ces corrections pour trouver les mesures corrigées : `mesures_corrigees = temperatures_vsd + correction`.

In [15]:
import numpy as np

# Partie 9 – Broadcasting (Mise à jour : Lignes = Capteurs)
# 1. Créer la matrice 3x3 (3 capteurs, 3 heures)
np.random.seed(42)

temperatures_3x3 = np.round(np.random.uniform(20, 30, size=(3, 3)), 2)

print("Les températures mises à jours sont: ", temperatures_3x3)

# 2. Appliquer les corrections (Broadcasting)

correction = np.array([1, -0.5, 0.2])
mesures_corrigees = temperatures_3x3 + correction
print("Températures corrigées :", mesures_corrigees)

# Vérification
print("Différence (corrigé - original) :")
print(mesures_corrigees - temperatures_3x3)


Les températures mises à jours sont:  [[23.75 29.51 27.32]
 [25.99 21.56 21.56]
 [20.58 28.66 26.01]]
Températures corrigées : [[24.75 29.01 27.52]
 [26.99 21.06 21.76]
 [21.58 28.16 26.21]]
Différence (corrigé - original) :
[[ 1.  -0.5  0.2]
 [ 1.  -0.5  0.2]
 [ 1.  -0.5  0.2]]
