# Atelier NumPy - IoT & Capteurs

## Contexte
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Ces capteurs mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. Les données collectées doivent être préparées et analysées avant d'être transmises à un futur système de Machine Learning chargé de détecter des situations anormales.
## Objectif général de l'atelier
L'objectif de cet atelier est de maîtriser les bases de **NumPy** (Numerical Python), la bibliothèque fondamentale pour le calcul scientifique en Python. 
À travers cet atelier, nous allons apprendre à :
- Manipuler des tableaux multidimensionnels (vecteurs et matrices).
- Effectuer des opérations mathématiques vectorisées (sans boucles `for`).
- Extraire, filtrer et transformer des données numériques efficacement.
## Structure du notebook
Ce notebook est découpé en plusieurs parties. Chaque partie correspond à une fonctionnalité précise (création de données, indexation, filtrage, calculs statistiques, etc.). 
Les résultats seront sauvegardés et poussés sur GitHub au fur et à mesure.

# Partie 1 : Listes Python vs tableaux NumPy

## Objectif de la partie
Avant de plonger dans les fonctionnalités avancées de NumPy, nous devons comprendre **pourquoi** nous utilisons cette bibliothèque plutôt que les listes classiques de Python.
## Ce qui est attendu
Nous disposons des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8.
1. Nous allons créer une **liste Python** classique pour stocker ces valeurs.
2. Nous allons créer un **tableau NumPy** équivalent.
3. Nous allons multiplier ces deux collections par 2.
4. Nous observerons et noterons la **différence fondamentale** dans le comportement

In [1]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.6 MB 1.7 MB/s eta 0:00:07
   ---- ----------------------------------- 1.6/12.6 MB 1.8 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.6 MB 1.8 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.6 MB 1.9 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.6 MB 1.9 MB/s eta 0:00:06
   ---------- ----------------------------- 3.4/12.6 MB 1.8 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.6 MB 1.8 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.6 MB 1.8 MB/s eta 0:00:05
   -------------- --


[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

#Création de liste python et du tableau numpy
temp_py = [24.5, 25.1, 26.3, 27.0, 25.8]
temp_nump = np.array(temp_py)
print("liste_python:" , temp_py)
print("numpy_array:" , temp_nump)

#Multiplication par 2
mult_py = temp_py * 2
mult_nump = temp_nump * 2
print( "liste_python*2:" , mult_py)
print("numpy_array*2:" , mult_nump)

liste_python: [24.5, 25.1, 26.3, 27.0, 25.8]
numpy_array: [24.5 25.1 26.3 27.  25.8]
liste_python*2: [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
numpy_array*2: [49.  50.2 52.6 54.  51.6]


Nous observons et notons la **différence fondamentale** dans le comportement :
   - La liste Python va dupliquer les éléments lors de la multiplication par 2(elle s'allonge).
   - Le tableau NumPy va multiplier mathématiquement chaque valeur de la liste par 2 (calcul vectoriel).

# Partie 2 – Création des données

## Objectif de la partie
Maintenant que nous avons compris la différence entre une liste Python et un tableau NumPy, nous allons apprendre à **générer** des tableaux de données sans avoir à les écrire un par un. 
Dans la vraie vie (et dans l'atelier), on a souvent besoin de créer des tableaux de zéros, de nombres alignés, ou de valeurs aléatoires pour simuler des données de capteurs.
## Ce qui est attendu
Nous allons utiliser les fonctions de création de NumPy pour répondre aux 7 questions suivantes. Chaque question correspond à une situation concrète

In [ ]:
import numpy as np

#Partie 2: Création de données
# 1. Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro
temp_initiale = np.zeros(10)
# 2. Créer un tableau contenant 10 valeurs égales à 1
table_1= np.ones(10)
# 3. Créer un tableau de 10 valeurs initialisées à 25.
table_25 = np.full(10, 25)
# 4. Créer une matrice identité de taille 5 × 5
mat_id = np.eye (5,5)
# 5. Créer les 24 heures (de 0 à 23) de mesure d’une journée
heures = np.arange(24)
# 6. Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C
temp_degrés = np.linspace(20, 30, 10)
# 7. Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles
np.random.seed(42)
temp_aléatoires = np.random.uniform(20, 30, 100)

#Affichage des résultats
print("1. Température initiale :", temp_initiale)
print("2. Tableau de 1s :", table_1)
print("3. Tableau de 25s :", table_25)
print("4. Matrice identité :\n", mat_id)
print("5. Heures :", heures)
print("6. Températures régulières : \n", temp_degrés)
print("7. Températures aléatoires: \n", temp_aléatoires)

1. Température initiale : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2. Tableau de 1s : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
3. Tableau de 25s : [25 25 25 25 25 25 25 25 25 25]
4. Matrice identité :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5. Heures : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
6. Températures régulières : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]
7. Températures aléatoires: [23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.976721

# Partie 3 – Exploration des tableaux

## Objectif de la partie
Maintenant que nous savons créer des tableaux de données, nous devons apprendre à les **explorer** et à comprendre leur structure. Dans la vraie vie, quand on reçoit un jeu de données (un tableau NumPy), on a besoin de savoir immédiatement :
- Combien de dimensions il a (est-ce un simple vecteur, une matrice, ou un tableau à plusieurs dimensions ?)
- Combien de valeurs il contient au total.
- Quel est le type des données (nombres entiers, décimaux, texte ?).
- Quelle est sa forme (ex: 24 lignes, ou 24 valeurs sur une seule ligne ?).
Ces informations sont essentielles avant de faire le moindre calcul ou la moindre modification.
## Ce qui est attendu
Nous allons utiliser le tableau des 24 températures d'une journée, créé aléatoirement, puis nous interrogerons ses propriétés à l'aide des attributs suivants :
- `.ndim` : pour connaître le nombre de dimensions.
- `.size` : pour connaître le nombre total d'éléments.
- `.dtype` : pour connaître le type de données (int, float, etc.).
- `.shape` : pour connaître la forme du tableau (nombre de lignes, de colonnes).
L'objectif est de prendre l'habitude de toujours "tâter" les données avant de les manipuler.

In [3]:
import numpy as np
# Partie 3: Exploration des tableaux
# 1.Créer aléatoirement un tableau représentant les 24 températures d'une journée
np.random.seed(42)
temp_journée = np.random.uniform(20, 30, 24)
# 2. Déterminer les propriétés suivantes du tableau
# dimension du tableau
dimension = temp_journée.ndim
# nombre de valeurs dans le tableau
nombre_valeurs = temp_journée.size
# type de données du tableau
type_donnees = temp_journée.dtype
# forme du tableau  
forme = temp_journée.shape

# 3. Afficher les résultats
print ("La dimension du tableau est :", dimension)
print ("Le nombre de valeurs dans le tableau est :", nombre_valeurs)
print ("Le type de données du tableau est :", type_donnees)
print ("La forme du tableau est :", forme)

La dimension du tableau est : 1
Le nombre de valeurs dans le tableau est : 24
Le type de données du tableau est : float64
La forme du tableau est : (24,)
